"""add registration_requests table

Revision ID: 62f99f5f7dc2
Revises: 24168a0ccc86
Create Date: 2025-07-27 12:20:57.279370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f99f5f7dc2'
down_revision: Union[str, Sequence[str], None] = '24168a0ccc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('schools_code_key'), 'schools', type_='unique')
    op.drop_constraint(op.f('schools_name_key'), 'schools', type_='unique')
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.create_unique_constraint(op.f('schools_name_key'), 'schools', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('schools_code_key'), 'schools', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
